# File: src/reporting/generator.py
import io
import base64
import plotly.graph_objects as go
from xhtml2pdf import pisa
from datetime import datetime

def create_snapshot_base64(time_arr, volt_arr, title="Snapshot"):
    """
    Vẽ lại đoạn sóng thành ảnh tĩnh (PNG) và trả về chuỗi Base64 để nhúng vào HTML.
    """
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=time_arr, y=volt_arr, 
        mode='lines', 
        line=dict(color='#dc2626', width=1.5) # Màu đỏ cho vùng bệnh lý
    ))
    
    # Tối giản hóa đồ thị để in báo cáo cho đẹp
    fig.update_layout(
        title=dict(text=title, font=dict(size=12)),
        margin=dict(l=40, r=20, t=30, b=30),
        xaxis=dict(title="Time (ms)", showgrid=True, gridcolor='#f3f4f6'),
        yaxis=dict(title="µV", showgrid=True, gridcolor='#f3f4f6'),
        template="plotly_white",
        width=600, height=200 # Kích thước ảnh
    )
    
    # Xuất ảnh ra bytes (Sử dụng Kaleido engine)
    img_bytes = fig.to_image(format="png", scale=2) # Scale=2 để ảnh nét hơn khi in
    return base64.b64encode(img_bytes).decode('utf-8')

def generate_pdf_buffer(patient_info, rec_info, labels_data):
    """
    Tạo file PDF báo cáo từ dữ liệu.
    - patient_info: dict thông tin bệnh nhân
    - rec_info: dict thông tin bản ghi
    - labels_data: list các dict chứa {stats, time_arr, volt_arr, label_type...}
    """
    
    # 1. Tạo HTML Template (CSS + Nội dung)
    html_content = f"""
    <html>
    <head>
        <style>
            @page {{ size: A4; margin: 2cm; }}
            body {{ font-family: Helvetica, sans-serif; color: #333; }}
            h1 {{ color: #1e3a8a; border-bottom: 2px solid #1e3a8a; padding-bottom: 5px; }}
            h2 {{ font-size: 16px; margin-top: 20px; color: #1f2937; background-color: #f3f4f6; padding: 5px; }}
            .info-table {{ width: 100%; margin-bottom: 20px; }}
            .info-table td {{ padding: 5px; vertical-align: top; }}
            .label-box {{ border: 1px solid #e5e7eb; margin-bottom: 15px; padding: 10px; page-break-inside: avoid; }}
            .stats {{ font-size: 12px; color: #4b5563; margin-bottom: 5px; }}
            .img-container {{ text-align: center; margin-top: 5px; }}
            .footer {{ position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #9ca3af; }}
        </style>
    </head>
    <body>
        <h1>EMG LABORATORY REPORT</h1>
        
        <table class="info-table">
            <tr>
                <td><strong>Họ tên:</strong> {patient_info.get('full_name', 'Unknown')}</td>
                <td><strong>Mã ID:</strong> {patient_info.get('patient_code', '---')}</td>
            </tr>
            <tr>
                <td><strong>Ngày đo:</strong> {rec_info.get('visit_date', '---')}</td>
                <td><strong>Bài test:</strong> {rec_info.get('test_name', '---')}</td>
            </tr>
             <tr>
                <td><strong>Bác sĩ/KTV:</strong> ADMIN</td>
                <td><strong>Ngày in:</strong> {datetime.now().strftime("%d/%m/%Y %H:%M")}</td>
            </tr>
        </table>
        
        <hr style="border: 0; border-top: 1px solid #ddd;" />
        
        <h2>KẾT QUẢ PHÂN TÍCH CHI TIẾT ({len(labels_data)} vùng)</h2>
    """

    # 2. Vòng lặp tạo ảnh và thông tin cho từng nhãn
    if not labels_data:
        html_content += "<p><em>Không có vùng bất thường nào được ghi nhận.</em></p>"
    else:
        for i, lbl in enumerate(labels_data, 1):
            # Tạo ảnh snapshot
            img_b64 = create_snapshot_base64(
                lbl['time_arr'], lbl['volt_arr'], 
                title=f"Vùng #{i}: {lbl['trace_id']} ({lbl['start_ms']:.1f}ms - {lbl['end_ms']:.1f}ms)"
            )
            
            stats = lbl.get('stats', {})
            html_content += f"""
            <div class="label-box">
                <div class="stats">
                    <strong>Loại:</strong> <span style="color:red">{lbl['label_type']}</span> | 
                    <strong>P2P:</strong> {stats.get('p2p_uv', 0)} µV | 
                    <strong>RMS:</strong> {stats.get('rms_uv', 0)} µV | 
                    <strong>Duration:</strong> {stats.get('duration_ms', 0)} ms
                </div>
                <div class="img-container">
                    <img src="data:image/png;base64,{img_b64}" width="550" />
                </div>
            </div>
            """

    html_content += """
        <div class="footer">
            Report generated by EMG Lab Software v1.2
        </div>
    </body>
    </html>
    """
    
    # 3. Convert HTML -> PDF Bytes
    pdf_buffer = io.BytesIO()
    pisa_status = pisa.CreatePDF(io.StringIO(html_content), dest=pdf_buffer)
    
    if pisa_status.err:
        return None
        
    pdf_buffer.seek(0)
    return pdf_buffer